export const dropdownData:any = {
    country: 
        [
            { key: 'Austria', text: 'Austria', value: 'Austria' }, 
            { key: 'Belarus', text: 'Belarus', value: 'Belarus' },
            { key: 'Denmark', text: 'Denmark', value: 'Denmark' },
            { key: 'France', text: 'France', value: 'France' },
            { key: 'Germany', text: 'Germany', value: 'Germany' },
            { key: 'Italy', text: 'Italy', value: 'Italy' },
            { key: 'Poland', text: 'Poland', value: 'Poland' },
            { key: 'Russia', text: 'Russia', value: 'Russia' },
            { key: 'Spain', text: 'Spain', value: 'Spain' },
            { key: 'Sweden', text: 'Sweden', value: 'Sweden' },
            { key: 'Ukraine', text: 'Ukraine', value: 'Ukraine' },
        ],
    city:
        [
            { key: 'Vienna', text: 'Vienna', value: 'Vienna', id: 'Austria' },
            { key: 'Graz', text: 'Graz', value: 'Graz', id: 'Austria' },
            { key: 'Linz', text: 'Linz', value: 'Linz', id: 'Austria' },
            { key: 'Salzburg', text: 'Salzburg', value: 'Salzburg', id: 'Austria' },
            { key: 'Minsk', text: 'Minsk', value: 'Minsk', id: 'Austria' }, 
            { key: 'Homyel', text: 'Homyel', value: 'Homyel', id: 'Belarus' },
            { key: 'Mogilev', text: 'Mogilev', value: 'Mogilev', id: 'Belarus' }, 
            { key: 'Brest', text: 'Brest', value: 'Brest', id: 'Belarus' }, 
            { key: 'Baranovichi', text: 'Baranovichi', value: 'Baranovichi', id: 'Belarus' }, 
            { key: 'Pinsk', text: 'Pinsk', value: 'Pinsk', id: 'Belarus' },
            { key: 'Copenhagen', text: 'Copenhagen', value: 'Copenhagen', id: 'Denmark' }, 
            { key: 'Odense', text: 'Odense', value: 'Odense', id: 'Denmark' }, 
            { key: 'Aalborg', text: 'Aalborg', value: 'Aalborg', id: 'Denmark' }, 
            { key: 'Horsens', text: 'Horsens', value: 'Horsens', id: 'Denmark' }, 
            { key: 'Vejle', text: 'Vejle', value: 'Vejle', id: 'Denmark' }, 
            { key: 'Paris', text: 'Paris', value: 'Paris', id: 'France' },
            { key: 'Marseille', text: 'Marseille', value: 'Marseille', id: 'France' },
            { key: 'Lyon', text: 'Lyon', value: 'Lyon', id: 'France' },
            { key: 'Toulouse', text: 'Toulouse', value: 'Toulouse', id: 'France' },
            { key: 'Strasbourg', text: 'Strasbourg', value: 'Strasbourg', id: 'France' },
            { key: 'Berlin', text: 'Berlin', value: 'Berlin', id: 'Germany' },
            { key: 'Hamburg', text: 'Hamburg', value: 'Hamburg', id: 'Germany' },
            { key: 'Frankfurt', text: 'Frankfurt', value: 'Frankfurt', id: 'Germany' },
            { key: 'Stuttgart', text: 'Stuttgart', value: 'Stuttgart', id: 'Germany' },
            { key: 'Bremen', text: 'Bremen', value: 'Bremen', id: 'Germany' },
            { key: 'Rome', text: 'Rome', value: 'Rome', id: 'Italy' },
            { key: 'Milan', text: 'Milan', value: 'Milan', id: 'Italy' },
            { key: 'Naples', text: 'Naples', value: 'Naples', id: 'Italy' },
            { key: 'Turin', text: 'Turin', value: 'Turin', id: 'Italy' },
            { key: 'Palermo', text: 'Palermo', value: 'Palermo', id: 'Italy' },
            { key: 'Warsaw', text: 'Warsaw', value: 'Warsaw', id: 'Poland' },
            { key: 'Krakow', text: 'Krakow', value: 'Krakow', id: 'Poland' },
            { key: 'Poznan', text: 'Poznan', value: 'Poznan', id: 'Poland' },
            { key: 'Lublin', text: 'Lublin', value: 'Lublin', id: 'Poland' },
            { key: 'Katowice', text: 'Katowice', value: 'Katowice', id: 'Poland' },
            { key: 'Moskow', text: 'Moskow', value: 'Moskow', id: 'Russia' },
            { key: 'St Petersburg', text: 'St Petersburg', value: 'St Petersburg', id: 'Russia' },
            { key: 'Novosibirsk', text: 'Novosibirsk', value: 'Novosibirsk', id: 'Russia' },
            { key: 'Samara', text: 'Samara', value: 'Samara', id: 'Russia' },
            { key: 'Omsk', text: 'Omsk', value: 'Omsk', id: 'Russia' },
            { key: 'Madrid', text: 'Madrid', value: 'Madrid', id: 'Spain' },
            { key: 'Barcelona', text: 'Barcelona', value: 'Barcelona', id: 'Spain' },
            { key: 'Valencia', text: 'Valencia', value: 'Valencia', id: 'Spain' },
            { key: 'Seville', text: 'Seville', value: 'Seville', id: 'Spain' },
            { key: 'Zaragoza', text: 'Zaragoza', value: 'Zaragoza', id: 'Spain' },
            { key: 'Stockholm', text: 'Stockholm', value: 'Stockholm', id: 'Sweden' },
            { key: 'Gothenburg', text: 'Gothenburg', value: 'Gothenburg', id: 'Sweden' },
            { key: 'Malmo', text: 'Malmo', value: 'Malmo', id: 'Sweden' },
            { key: 'Uppsala', text: 'Uppsala', value: 'Uppsala', id: 'Sweden' },
            { key: 'Sollentuna', text: 'Sollentuna', value: 'Sollentuna', id: 'Sweden' },
            { key: 'Kyiv', text: 'Kyiv', value: 'Kyiv', id: 'Ukraine' },
            { key: 'Kharkiv', text: 'Kharkiv', value: 'Kharkiv', id: 'Ukraine' },
            { key: 'Odesa', text: 'Odesa', value: 'Odesa', id: 'Ukraine' },
            { key: 'Lviv', text: 'Lviv', value: 'Lviv', id: 'Ukraine' },
            { key: 'Zaporizhia', text: 'Zaporizhia', value: 'Zaporizhia', id: 'Ukraine' },
        ]
}